/**
 * Native desktop audio capture and Session composition for Node.js.
 *
 * @packageDocumentation
 */
export { runtimeCompatibility, type RuntimeCompatibility } from '../compatibility.js';
export {
  ClockDomainId,
  ConnectorId,
  EndpointId,
  OperatorInstanceId,
  RouteId,
  RuntimeSessionId,
  SidecarId,
  SourceId,
  SourceInstanceId,
  StemId,
  StreamId,
  type ClockDomainKind,
  type ClockDomainOrigin,
} from './identity.js';
export {
  CaptureError,
  ExtensionError,
  SessionDeclarationError,
  SourceError,
  PocketStationError,
  StreamError,
  StreamInUseError,
  StreamModeError,
  SidecarBackpressureError,
  SidecarError,
  SidecarProtocolError,
  SidecarTimeoutError,
} from './errors.js';
export {
  ExtensionAbiVersion,
  ExtensionDescriptor,
  ExtensionPort,
  type ExtensionDescriptorOptions,
  type ExtensionKind,
  type ExtensionPortDirection,
  type ExtensionPortOptions,
  type NativeExtensionLibrary,
  type NativeExtensionRegistration,
} from './extensions.js';
export {
  AudioInput,
  AudioInputAbortError,
  AudioInputBufferError,
  AudioInputCancelledError,
  AudioInputClosedError,
  AudioInputConfigurationError,
  AudioInputError,
  AudioInputFullError,
  AudioInputTimeoutError,
  OutputCancelledError,
  OutputGeneration,
  OutputGenerationLimitError,
  OutputOwnershipError,
  type PcmSource,
  type AudioInputConfig,
  type AudioInputObservations,
  type AudioInputOptions,
  type AudioInputSamples,
  type AudioInputTryWriteOptions,
  type AudioInputWriteOptions,
} from './application-audio.js';
export {
  EventInput,
  EventInputClosedError,
  EventInputError,
  EventInputFullError,
  type EventInputObservations,
  type EventInputOptions,
  type EventInputWriteOptions,
} from './event-input.js';
export {
  Capture,
  capture,
  type CaptureAudioBatchOptions,
  type CaptureAudioWaitOptions,
  type CaptureOptions,
  type CaptureSettings,
} from './capture.js';
export {
  Connector,
  ConnectorConfigurationConstraint,
  ConnectorConfigurationField,
  ConnectorConfigurationRequirement,
  ConnectorConfigurationSchema,
  ConnectorConfigurationValue,
  ConnectorConfigurationValueKind,
  ConnectorContext,
  ConnectorDeliveryReadiness,
  ConnectorDeliveryOutcome,
  ConnectorDriver,
  ConnectorError,
  ConnectorErrorStage,
  ConnectorHealth,
  ConnectorManifest,
  ConnectorRecovery,
  ConnectorRetryability,
  ConnectorShutdownMode,
  ConnectorWorker,
  RegisteredConnector,
  connector,
  type AudioConnectorHandler,
  type ConnectorBatchOutcome,
  type ConnectorCapability,
  type ConnectorAudioFrame,
  type ConnectorConfigurationFieldOptions,
  type ConnectorConfigurationInput,
  type ConnectorDeadlines,
  type ConnectorDriverBuilder,
  type ConnectorDriverFactory,
  type ConnectorFactory,
  type ConnectorHandler,
  type ConnectorErrorSnapshot,
  type ConnectorInputDescriptor,
  type ConnectorItem,
  type ConnectorManifestOptions,
  type ConnectorObservations,
  type ConnectorOptions,
  type ConnectorPreparationGroup,
  type ConnectorRequirement,
  type ConnectorRuntimeObservations,
  type ConnectorSend,
  type ConnectorServiceStatus,
  type ConnectorWorkerBuilder,
} from './connector.js';
export {
  EndpointDriverError,
  EndpointDriverObservations,
  EndpointFailureRetryability,
  EndpointManifest,
  EndpointPortInput,
  EndpointPrepareContext,
  EndpointProvider,
  EndpointShutdownMode,
  EndpointStartGate,
  PreparedEndpointDriver,
  RegisteredEndpoint,
  RunningEndpointDriver,
  type EndpointConfigurationInput,
  type EndpointDeadlines,
  type EndpointDriverBuilder,
  type EndpointDriverFactory,
  type EndpointDriverItem,
  type EndpointPreparationGroup,
  type EndpointRuntimeObservations,
} from './endpoint.js';
export {
  EndpointFactory,
  OperatorEmission,
  OperatorFactory,
  SourceEmission,
  SourceFactory,
  defineEndpoint,
  defineOperator,
  defineSource,
  type EndpointAudioItem,
  type EndpointContext,
  type EndpointDeliveryOutcome,
  type EndpointItem,
  type EndpointProviderOptions,
  type EndpointFactoryOptions,
  type EndpointNode,
  type EndpointReceive,
  type EndpointSignalItem,
  type OperatorContext,
  type OperatorEmissionInput,
  type OperatorFactoryOptions,
  type OperatorNode,
  type SourceContext,
  type SourceDriver,
  type SourceDriverPrepareContext,
  type SourceEmissionInput,
  type SourceEmissionOptions,
  type SourceFactoryOptions,
} from './provider.js';
export {
  OperatorDeadlines,
  OperatorManifest,
  OperatorPortContext,
  OperatorPrepareContext,
  OperatorProvider,
  RegisteredOperator,
  operator,
  type AuthoredOperatorNode,
  type OperatorConfigValidator,
  type OperatorHandler,
  type OperatorNodeBuilder,
  type OperatorNodeFactory,
} from './operator.js';
export {
  RegisteredSource,
  SourceCancellation,
  SourceDeadlines,
  SourceManifest,
  SourceOutputIdentity,
  SourcePrepareContext,
  SourceProvider,
  source,
  type AuthoredSourceDriver,
  type SourceConfigValidator,
  type SourceDriverBuilder,
  type SourceDriverFactory,
  type SourceIterableFactory,
} from './source.js';
export {
  EventStream,
  type EndpointFailure,
  type EndpointFailureEvent,
  type EndpointFailureStage,
  type EventReadOptions,
  type FinalizationFailureStage,
  type LifecycleEvent,
  type RollbackFailureStage,
  type SessionControlFailure,
  type SessionControlFailureEvent,
  type SessionEvent,
  type SessionState,
  type SourceFailure,
  type SourceFailureEvent,
  type TerminalEvent,
} from './events.js';
export {
  evaluateSourceActivity,
  evaluateSourceSignal,
  SampleRepresentation,
  SessionTrace,
  type OpenedNativeFormat,
  type AudioReentryMetrics,
  type DerivedRouteMetrics,
  type EndpointMetrics,
  type EventQueueMetrics,
  type ExternalSourceMetrics,
  type LatencyHistogram,
  type OperatorInputMetrics,
  type OperatorMetrics,
  type OperatorWorkerMetrics,
  type PolledAudioMetrics,
  type RecordingDiscontinuity,
  type RecordingOutcome,
  type RecordingStemOutcome,
  type RouteDeliveryMetrics,
  type RouteMetrics,
  type SessionMetrics,
  type SessionTraceOutcome,
  type SessionTraceRecord,
  type SessionTraceRecordKind,
  type SessionTraceValidation,
  type SignalQueueMetrics,
  type SourceMetrics,
  type SourceNativeFormatObservation,
  type SourceActivityObservation,
  type SourceActivityPolicy,
  type SourceActivityEvaluation,
  type SourceActivityState,
  type SourceSignalObservation,
  type SourceSignalPolicy,
  type SourceSignalEvaluation,
  type SourceSignalState,
  type SourceReplacementObservation,
} from './observations.js';
export {
  Codec,
  DeliveryPolicy,
  EndpointDefinition,
  MediaCaps,
  Operator,
  PortSpec,
  RouteSettings,
  SignalSpec,
  secret,
  type AudioCaps,
  type BinaryFormat,
  type ChannelLayout,
  type ClockDomain,
  type Configuration,
  type ConfigurationValue,
  type DeliverySemantics,
  type EventFormat,
  type FrameOwnership,
  type LossPolicy,
  type MediaKind,
  type Multiplicity,
  type PortDirection,
  type QueuePressure,
  type RouteObservability,
  type SecretValue,
  type SignalKind,
  type SignalOptions,
  type TextFormat,
} from './graph.js';
export {
  DerivedStream,
  Endpoint,
  OperatorInput,
  OperatorInstance,
  RelayPublisher,
  RunningSession,
  Session,
  SessionStartError,
  SourceOutput,
  SourceInstance,
  Stem,
  type CompileDiagnostic,
  type RelayIceServer,
  type RelayPublisherOptions,
  type SessionOptions,
  type SessionTraceOptions,
  type SourceConfiguration,
  type StopResult,
  type SourceReplacement,
} from './session.js';
export {
  SidecarConnection,
  SidecarHandle,
  SidecarMessage,
  SidecarProcess,
  SidecarSnapshot,
  SidecarStream,
  type SidecarDeadlines,
  type SidecarMessageKind,
  type SidecarProcessOptions,
  type SidecarProtocolLimits,
  type SidecarReadResult,
  type SidecarSignalOptions,
  type SidecarState,
} from './sidecar.js';
export {
  BusSubscription,
  SignalStream,
  type AudioSignalPayload,
  type BytesSignalPayload,
  type SignalDerivation,
  type SignalEnvelope,
  type SignalLineage,
  type SignalPayload,
  type SignalReadResult,
  type SignalSubscriptionMetrics,
  type SignalTiming,
  type TextSignalPayload,
} from './signals.js';
export {
  ApplicationPolicyObservation,
  CaptureCapabilityState,
  CaptureOpenOutcome,
  CapturePermissionLifecycle,
  CapturePermissionTransitionKind,
  CaptureScopeKind,
  CaptureSessionGrant,
  DiscoveredSource,
  PermissionObservation,
  Platform,
  ProcessTreeScope,
  SelectorPersistenceScope,
  Source,
  SourceFailureClass,
  SourceIdentityStrength,
  SourceKind,
  SourceQuery,
  SourceRecoveryRequirement,
  SourceRuntimeEventKind,
  SourceSelectorKind,
  SourceState,
  applicationCaptureAvailable,
  discoverSources,
  microphonePermissionObservation,
  type ApplicationSelection,
  type AuthorizationOptions,
  type CaptureAuthorizationSnapshot,
  type CapturePermissionTransition,
  type CaptureScope,
  type ProcessInstanceSelector,
  type SourceQueryInput,
  type SourceRuntimeEvent,
  type SourceSelectorValue,
  type StableSourceId,
} from './sources.js';
export {
  END_OF_STREAM,
  AudioBatch,
  AudioStream,
  EndOfStream,
  StreamAbortError,
  type AudioBatchReadResult,
  type AudioFrame,
  type AudioReadResult,
  type ClockDomainDescriptor,
  type StreamReadOptions,
} from './streams.js';
