/**
 * Native desktop audio capture and Session composition for Node.js.
 *
 * @packageDocumentation
 */
export {
  ExtensionError,
  PocketStationError,
  SidecarBackpressureError,
  SidecarError,
  SidecarProtocolError,
  SidecarTimeoutError,
} from './errors.js';
export {
  ExtensionAbiVersion,
  ExtensionDescriptor,
  ExtensionPort,
  type ExtensionDescriptorOptions,
  type ExtensionKind,
  type ExtensionPortDirection,
  type ExtensionPortOptions,
  type NativeExtensionLibrary,
  type NativeExtensionRegistration,
} from './extensions.js';
export {
  AudioInput,
  AudioInputAbortError,
  AudioInputBufferError,
  AudioInputCancelledError,
  AudioInputClosedError,
  AudioInputConfigurationError,
  AudioInputError,
  AudioInputFullError,
  AudioInputTimeoutError,
  type AudioInputConfig,
  type AudioInputObservations,
  type AudioInputOptions,
  type AudioInputSamples,
  type AudioInputTryWriteOptions,
  type AudioInputWriteOptions,
} from './application-audio.js';
export {
  EventStream,
  type EndpointFailureEvent,
  type EventReadOptions,
  type LifecycleEvent,
  type SessionControlFailureEvent,
  type SessionEvent,
  type SessionState,
  type SourceFailure,
  type SourceFailureEvent,
  type TerminalEvent,
} from './events.js';
export {
  Codec,
  DeliveryPolicy,
  EndpointDefinition,
  MediaCaps,
  Operator,
  PortSpec,
  RouteSettings,
  SignalSpec,
  secret,
  type AudioCaps,
  type BinaryFormat,
  type ChannelLayout,
  type ClockDomain,
  type Configuration,
  type ConfigurationValue,
  type DeliverySemantics,
  type EventFormat,
  type FrameOwnership,
  type LossPolicy,
  type MediaKind,
  type Multiplicity,
  type PortDirection,
  type QueuePressure,
  type RouteObservability,
  type SecretValue,
  type SignalKind,
  type SignalOptions,
  type TextFormat,
} from './graph.js';
export {
  DerivedStream,
  Endpoint,
  OperatorInput,
  OperatorInstance,
  RunningSession,
  Session,
  SessionStartError,
  SourceOutput,
  SourceInstance,
  Stem,
  type CompileDiagnostic,
  type SessionOptions,
  type SourceConfiguration,
  type StopResult,
} from './session.js';
export {
  SidecarConnection,
  SidecarHandle,
  SidecarMessage,
  SidecarProcess,
  SidecarSnapshot,
  SidecarStream,
  type SidecarDeadlines,
  type SidecarMessageKind,
  type SidecarProcessOptions,
  type SidecarProtocolLimits,
  type SidecarReadResult,
  type SidecarSignalOptions,
  type SidecarState,
} from './sidecar.js';
export {
  BusSubscription,
  SignalStream,
  type AudioSignalPayload,
  type BytesSignalPayload,
  type SignalDerivation,
  type SignalEnvelope,
  type SignalLineage,
  type SignalPayload,
  type SignalReadResult,
  type SignalSubscriptionMetrics,
  type SignalTiming,
  type TextSignalPayload,
} from './signals.js';
export {
  CapturePermissionLifecycle,
  DiscoveredSource,
  Source,
  applicationCaptureAvailable,
  discoverSources,
  microphonePermissionObservation,
  type ApplicationPolicyObservation,
  type ApplicationSelection,
  type AuthorizationOptions,
  type CaptureAuthorizationSnapshot,
  type CaptureCapabilityState,
  type CaptureOpenOutcome,
  type CapturePermissionTransition,
  type CaptureScope,
  type CaptureSessionGrant,
  type PermissionObservation,
  type Platform,
  type ProcessInstanceSelector,
  type ProcessTreeScope,
  type SelectorPersistenceScope,
  type SourceIdentityStrength,
  type SourceKind,
  type SourceQuery,
  type SourceState,
  type StableSourceId,
} from './sources.js';
export {
  END_OF_STREAM,
  AudioStream,
  EndOfStream,
  StreamAbortError,
  type AudioFrame,
  type AudioReadResult,
  type StreamReadOptions,
} from './streams.js';
