/**
 * Native desktop audio capture and Session composition for Node.js.
 *
 * @packageDocumentation
 */
export {
  aecAvailable,
  EchoCancelledAudio,
  PlaybackReference,
  type EchoAudioInput,
  type EchoCancellationObservations,
  type EchoCancellationState,
  type PlaybackReferenceCoverage,
} from './aec.js';
export { RecordedAudio, RecordingClipWindow, type RecordedStem, type RecordingClip } from './recording.js';
export { RecordingClipError } from './errors.js';
export {
  RuntimeCompatibility,
  runtimeCompatibility,
  type RuntimeCompatibilityOptions,
} from '../compatibility.js';
export {
  ControlClient,
  ControlPlaneError,
  InvitationUnavailableError,
  SecretToken,
  SecretUrl,
  SessionId,
  type BusCredentialOptions,
  type BusState,
  type ControlClientOptions,
  type ControlFetch,
  type IceServer as ControlIceServer,
  type ControlRequestOptions,
  type CreateSessionOptions,
  type Invitation,
  type InvitationMetadata,
  type InvitationVisibility,
  type PublisherCredentialOptions,
  type PublisherCredentials,
  type RedeemedInvitation,
  type RedeemInvitationOptions,
  type SessionCredentials,
  type SessionSnapshot,
  type SubscriberCredentials,
  type SubscriptionState,
} from '../control/index.js';
export {
  ClockDomainId,
  ConnectorId,
  EndpointId,
  OperatorInstanceId,
  RouteId,
  RuntimeSessionId,
  SidecarId,
  SourceId,
  SourceInstanceId,
  StemId,
  StreamId,
  type ClockDomainKind,
  type ClockDomainOrigin,
} from './identity.js';
export {
  AudioInputAbortError,
  AudioInputBufferError,
  AudioInputCancelledError,
  AudioInputClosedError,
  AudioInputConfigurationError,
  AudioInputError,
  AudioInputFullError,
  AudioInputTimeoutError,
  CaptureError,
  ConnectorRuntimeError,
  EventInputClosedError,
  EventInputError,
  EventInputFullError,
  ExtensionError,
  GraphError,
  OperatorError,
  OutputCancelledError,
  OutputGenerationLimitError,
  OutputOwnershipError,
  PocketStationError,
  SessionCompileDiagnostic,
  SessionDeclarationError,
  SessionError,
  SessionRuntimeError,
  SessionStartError,
  SidecarBackpressureError,
  SidecarError,
  SidecarProtocolError,
  SidecarTimeoutError,
  SourceError,
  StreamError,
  StreamInUseError,
  StreamModeError,
  type SessionCompileDiagnosticOptions,
} from './errors.js';
export {
  ExtensionAbiVersion,
  ExtensionDescriptor,
  ExtensionPort,
  ExtensionPortDirection,
  ExtensionKind,
  type ExtensionDescriptorOptions,
  type LegacyExtensionDescriptorOptions,
  type ExtensionPortOptions,
  type NativeExtensionLibrary,
  type NativeExtensionRegistration,
} from './extensions.js';
export {
  AudioInput,
  OutputGeneration,
  type PcmSource,
  type AudioInputConfig,
  type AudioInputObservations,
  type AudioInputOptions,
  type AudioInputSamples,
  type AudioInputTryWriteOptions,
  type AudioInputWriteOptions,
} from './application-audio.js';
export {
  EventInput,
  type EventInputObservations,
  type EventInputOptions,
  type EventInputWriteOptions,
} from './event-input.js';
export {
  Capture,
  capture,
  type CaptureAudioBatchOptions,
  type CaptureAudioWaitOptions,
  type CaptureOptions,
  type CaptureSettings,
} from './capture.js';
export {
  Connector,
  ConnectorConfigurationConstraint,
  ConnectorConfigurationField,
  ConnectorConfigurationRequirement,
  ConnectorConfigurationSchema,
  ConnectorConfigurationValue,
  ConnectorConfigurationValueKind,
  ConnectorContext,
  ConnectorDeadlines,
  ConnectorDeliveryReadiness,
  ConnectorDeliveryOutcome,
  ConnectorDriver,
  ConnectorError,
  ConnectorErrorStage,
  ConnectorHealth,
  ConnectorManifest,
  ConnectorRecovery,
  ConnectorRetryability,
  ConnectorShutdownMode,
  ConnectorWorker,
  RegisteredConnector,
  connector,
  type AudioConnectorHandler,
  type ConnectorBatchOutcome,
  type ConnectorCapability,
  type ConnectorAudioFrame,
  type ConnectorConfigurationFieldOptions,
  type ConnectorConfigurationInput,
  type ConnectorDeadlinesInput,
  type ConnectorDeadlinesOptions,
  type ConnectorDriverBuilder,
  type ConnectorDriverFactory,
  type ConnectorFactory,
  type ConnectorHandler,
  type ConnectorErrorSnapshot,
  type ConnectorInputDescriptor,
  type ConnectorItem,
  type ConnectorManifestOptions,
  type ConnectorObservations,
  type ConnectorOptions,
  type ConnectorPreparationGroup,
  type ConnectorRequirement,
  type ConnectorRuntimeObservations,
  type ConnectorSend,
  type ConnectorServiceStatus,
  type ConnectorWorkerBuilder,
} from './connector.js';
export {
  EndpointDriverError,
  EndpointDriverObservations,
  EndpointFailureRetryability,
  EndpointManifest,
  EndpointPortInput,
  EndpointPrepareContext,
  EndpointProvider,
  EndpointShutdownMode,
  EndpointStartGate,
  PreparedEndpointDriver,
  RegisteredEndpoint,
  RunningEndpointDriver,
  type EndpointConfigurationInput,
  type EndpointDeadlines,
  type EndpointDriverBuilder,
  type EndpointDriverFactory,
  type EndpointDriverItem,
  type EndpointPreparationGroup,
  type EndpointRuntimeObservations,
} from './endpoint.js';
export {
  EndpointFactory,
  OperatorEmission,
  OperatorFactory,
  SourceEmission,
  SourceFactory,
  defineEndpoint,
  defineOperator,
  defineSource,
  type EndpointAudioItem,
  type EndpointContext,
  type EndpointDeliveryOutcome,
  type EndpointItem,
  type EndpointProviderOptions,
  type EndpointFactoryOptions,
  type EndpointNode,
  type EndpointReceive,
  type EndpointSignalItem,
  type OperatorContext,
  type OperatorEmissionInput,
  type OperatorFactoryOptions,
  type OperatorNode,
  type SourceContext,
  type SourceDriver,
  type SourceDriverPrepareContext,
  type SourceEmissionInput,
  type SourceEmissionOptions,
  type SourceFactoryOptions,
} from './provider.js';
export {
  OperatorDeadlines,
  OperatorManifest,
  OperatorPortContext,
  OperatorPrepareContext,
  OperatorProvider,
  RegisteredOperator,
  operator,
  type AuthoredOperatorNode,
  type OperatorConfigValidator,
  type OperatorHandler,
  type OperatorNodeBuilder,
  type OperatorNodeFactory,
} from './operator.js';
export {
  RegisteredSource,
  SourceCancellation,
  SourceDeadlines,
  SourceManifest,
  SourceOutputIdentity,
  SourcePrepareContext,
  SourceProvider,
  source,
  type AuthoredSourceDriver,
  type SourceConfigValidator,
  type SourceDriverBuilder,
  type SourceDriverFactory,
  type SourceIterableFactory,
} from './source.js';
export {
  PublisherActivation,
  ReceiverActivation,
  ReceiverInvitation,
  RelayError,
  RelaySession,
  RelayTimeoutError,
  type ReceiverInvitationOptions,
  type RelayActivationOptions,
  type RelaySessionOptions,
} from './relay.js';
export {
  EndpointFailureStage,
  EventStream,
  SessionComponentKind,
  SessionEventType,
  SessionFailureKind,
  SessionFinalizationStage,
  SessionLifecycleState,
  SessionRollbackStage,
  SessionTerminalState,
  type EndpointFailure,
  type EndpointFailureEvent,
  type EventReadOptions,
  type EventStreamOptions,
  type FinalizationFailureStage,
  type LifecycleEvent,
  type RollbackFailureStage,
  type SessionComponent,
  type SessionControlFailure,
  type SessionControlFailureEvent,
  type SessionEvent,
  type SessionEventFields,
  type SessionFailure,
  type SessionState,
  type SourceFailure,
  type SourceFailureEvent,
  type TerminalEvent,
} from './events.js';
export {
  EndpointObservationStage,
  evaluateSourceActivity,
  evaluateSourceSignal,
  SampleRepresentation,
  RecordingDiscontinuityKind,
  RecordingState,
  RouteLatencyMeasurement,
  RouteLatencyUnit,
  RouteObservationInterval,
  SessionTrace,
  SessionTraceConfiguration,
  SessionTraceRecordType,
  TerminationDisposition,
  type AudioReentryMetrics,
  type OpenedNativeFormat,
  type DerivedRouteMetrics,
  type EndpointMetrics,
  type EventQueueMetrics,
  type ExternalSourceMetrics,
  type LatencyHistogram,
  type OperatorInputMetrics,
  type OperatorMetrics,
  type OperatorWorkerMetrics,
  type PolledAudioMetrics,
  type RecordingDiscontinuity,
  type RecordingOutcome,
  type RecordingStemOutcome,
  type RelayPublishOutcome,
  type RouteDeliveryMetrics,
  type RouteMetrics,
  type SessionMetrics,
  type SessionTraceOutcome,
  type SessionTraceRecorderOutcome,
  type SessionTraceRecord,
  type SessionTraceValidation,
  type SignalQueueMetrics,
  type SourceMetrics,
  type SourceNativeFormatObservation,
  type SourceActivityObservation,
  type SourceActivityPolicy,
  type SourceActivityEvaluation,
  type SourceActivityState,
  type SourceSignalObservation,
  type SourceSignalPolicy,
  type SourceSignalEvaluation,
  type SourceSignalState,
  type SourceReplacementObservation,
} from './observations.js';
export {
  AudioCaps,
  BackpressurePolicy,
  BinaryFormat,
  ChannelLayout,
  ClockDomain,
  Codec,
  CopyPolicy,
  DeliveryPolicy,
  DeliverySemantics,
  EndpointDefinition,
  EndpointDescriptor,
  EndpointConfiguration,
  EventFormat,
  LossPolicy,
  MediaCaps,
  MediaKind,
  Multiplicity,
  Operator,
  OperatorConfiguration,
  PortDirection,
  PortSpec,
  RouteObservability,
  RouteSettings,
  SampleFormat,
  SignalSpec,
  SignalKind,
  SourceConfiguration,
  TextFormat,
  secret,
  type AudioCapsOptions,
  type Configuration,
  type ConfigurationInput,
  type ConfigurationValue,
  type FrameOwnership,
  type MediaFormat,
  type QueuePressure,
  type SecretValue,
  type SignalFormat,
  type SignalOptions,
  type SourceConfigurationInput,
} from './graph.js';
export {
  DerivedStream,
  Endpoint,
  OperatorInput,
  OperatorInstance,
  RelayPublisher,
  RelayRoute,
  RunningSession,
  Session,
  SourceOutput,
  SourceInstance,
  Stem,
  type CompileDiagnostic,
  type OperatorPortOptions,
  type RelayIceServer,
  type RelayPublisherOptions,
  type RouteInputOptions,
  type SessionOptions,
  type SessionTraceOptions,
  type StopResult,
  type SourceReplacement,
} from './session.js';
export {
  SidecarConnection,
  SidecarDeadlines,
  SidecarHandle,
  SidecarMessage,
  SidecarMessageKind,
  SidecarProcess,
  SidecarProcessSpec,
  SidecarProtocolLimits,
  SidecarSnapshot,
  SidecarState,
  SidecarStream,
  type SidecarDeadlinesOptions,
  type SidecarProcessOptions,
  type SidecarProtocolLimitsOptions,
  type SidecarReadResult,
  type SidecarSignalOptions,
} from './sidecar.js';
export {
  BusSubscription,
  STREAM_EOF,
  SignalStream,
  type AudioSignalPayload,
  type BytesSignalPayload,
  type SignalDerivation,
  type SignalEnvelope,
  type SignalLineage,
  type SignalPayload,
  type SignalAudioPayload,
  type SignalReadResult,
  type SignalSubscriptionMetrics,
  type SignalTiming,
  type TextSignalPayload,
} from './signals.js';
export {
  ApplicationPolicyObservation,
  CaptureCapabilityState,
  CaptureOpenOutcome,
  CapturePermissionLifecycle,
  CapturePermissionTransitionKind,
  CaptureScopeKind,
  CaptureSessionGrant,
  DiscoveredSource,
  PermissionObservation,
  Platform,
  ProcessTreeScope,
  SelectorPersistenceScope,
  Source,
  SourceFailureClass,
  SourceIdentityStrength,
  SourceKind,
  SourceQuery,
  SourceRecoveryRequirement,
  SourceRuntimeEventKind,
  SourceSelectorKind,
  SourceState,
  applicationCaptureAvailable,
  discoverSources,
  microphonePermissionObservation,
  type ApplicationSelection,
  type AuthorizationOptions,
  type CaptureAuthorizationSnapshot,
  type CapturePermissionTransition,
  type CaptureScope,
  type ProcessInstanceSelector,
  type SourceQueryInput,
  type SourceRuntimeEvent,
  type SourceSelectorValue,
  type StableSourceId,
} from './sources.js';
export {
  END_OF_STREAM,
  AudioBatch,
  AudioStream,
  EndOfStream,
  StreamAbortError,
  type AudioBatchReadResult,
  type AudioFrame,
  type AudioProcessing,
  type AudioReadResult,
  type ClockDomainDescriptor,
  type StreamReadOptions,
} from './streams.js';
